### ISSUE TITLE
Runs like crap on Firefox

### ISSUE THREAD

**Issue by 0n** [beclamide/gta-css#2]
No idea why, but it runs like crap on Firefox

**Comment by beclamide** [comment]
The graphics are definitely a bit jankier aren't they? It seems to be running fairly fast still though on 88.0.1 on OSX.

Which version and OS did you test it on?

**Comment by 0n** [comment]
> 
> 
> The graphics are definitely a bit jankier aren't they? It seems to be running fairly fast still though on 88.0.1 on OSX.
> 
> Which version and OS did you test it on?

I used Windows 8.1, it ran like crap on both Waterfox and Firefox but it ran fine on chromium based browsers like vivaldi and chrome
